# Generated by Django 5.0 on 2025-10-28 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clave_pin',
            field=models.CharField(default='0000', help_text='PIN de 4 dígitos numéricos', max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterUniqueTogether(
            name='marcacion',
            unique_together={('usuario', 'fecha', 'tipo')},
        ),
    ]
